---
name: 01 - Building Blocks v1.1

on:
  #push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful Step
        run: |
          echo "I will succes  now"
          exit 0
      - name: Wyswietlam pliki z 1 joba
        run: |
          ls -la
      - name: Say Goodbye
        run: |
          echo "This step will be skipped if the previous step fails"
